In [47]:
import numpy as np

a = np.random.randint(0, 10, 100).reshape(10, 10)
b = np.copy(a)
for i in range(len(a)):
    for j in range(len(a)):
        if a[i][j] == 0:
            zeroing(b, i, j)
print('Primary matrix')
print(a, end='\n\n\n\n\n')
print('Modified matrix')
print(b)


Primary matrix
[[8 2 6 3 4 8 5 9 7 1]
 [8 7 1 3 3 6 4 4 5 9]
 [0 5 5 5 9 1 7 1 9 7]
 [4 1 3 8 9 8 4 7 3 4]
 [6 4 6 8 0 6 8 1 2 2]
 [2 5 1 3 4 3 7 1 2 0]
 [1 0 2 4 3 3 3 9 6 5]
 [5 7 9 9 5 2 0 2 0 0]
 [9 5 9 8 1 4 3 9 2 1]
 [8 7 7 8 4 4 4 9 2 2]]




Modified matrix
[[0 0 0 3 0 8 5 0 0 1]
 [0 0 0 0 3 0 0 0 5 9]
 [0 0 0 0 0 0 0 1 9 7]
 [4 0 0 0 0 0 4 0 3 4]
 [6 4 0 0 0 0 0 1 0 0]
 [0 5 0 0 0 0 0 0 0 0]
 [1 0 0 4 0 0 0 0 0 0]
 [0 0 0 9 5 0 0 0 0 0]
 [0 5 9 0 1 0 0 0 0 0]
 [8 7 7 8 0 0 0 0 0 0]]


In [37]:
def zeroing(b, i, j):
    n,m = i,j
    
    while True:
        if n == 0 or m == 0:
            n,m = i,j
            break
        n -= 1
        m -= 1
        b[n][m] = 0
        
    while True:
        if n == 9 or m == 0:
            n,m = i,j
            break
        n += 1
        m -= 1
        b[n][m] = 0
        
    while True:
        if n == 9 or m == 9:
            n,m = i,j
            break
        n += 1
        m += 1
        b[n][m] = 0
        
    while True:
        if n == 0 or m == 9:
            break
        n -= 1
        m += 1
        b[n][m] = 0
        
    return b
    