In [11]:
import numpy as np
arr = np.random.randint(0, 10, 100).reshape(10, 10)

print(arr)
print('-------------')

pairs = []

for ind, a in enumerate(arr):
    for sub_ind, val in enumerate(a):
        if val == 0:
            pairs.append([ind, sub_ind])

def decider(pairs, x2, y2):
    for pair in pairs:
        x1 = pair[0]
        y1 = pair[1]
        if abs(x1 - x2) == abs(y1 - y2):
            return 'yes'
    
    return 'no'

for ind, a in enumerate(arr):
        for sub_ind, val in enumerate(a):
            res = decider(pairs, ind, sub_ind)
            if res == 'yes':
                a[sub_ind] = 0

print(arr)


[[8 2 4 3 0 2 8 9 6 0]
 [8 0 6 1 6 6 7 4 7 0]
 [7 3 6 3 9 3 0 5 7 8]
 [9 4 0 8 7 9 9 7 4 7]
 [4 5 0 7 3 4 9 9 9 0]
 [4 5 1 4 5 2 8 8 1 6]
 [0 6 7 7 2 1 0 2 7 6]
 [7 5 5 9 8 8 7 3 1 2]
 [5 3 9 2 8 0 5 1 5 1]
 [8 6 6 2 7 5 1 5 5 4]]
-------------
[[0 2 0 3 0 0 0 9 0 0]
 [0 0 6 0 0 0 0 0 0 0]
 [0 0 0 0 0 3 0 0 0 8]
 [0 0 0 0 7 0 0 0 0 0]
 [0 0 0 0 0 0 0 9 0 0]
 [0 0 0 0 0 0 8 0 0 0]
 [0 6 0 0 0 0 0 0 7 6]
 [7 0 0 0 0 0 0 0 1 2]
 [0 0 0 2 0 0 0 0 0 1]
 [0 0 6 0 0 5 0 0 0 0]]
