In [255]:
import numpy as np

a = np.random.randint(0, 10, 100).reshape(10, 10)
b = np.zeros( (10, 10) )
c= np.add(a,b)
c

array([[ 0.,  9.,  1.,  5.,  7.,  1.,  2.,  0.,  7.,  3.],
       [ 0.,  4.,  6.,  5.,  4.,  4.,  2.,  3.,  7.,  8.],
       [ 0.,  3.,  9.,  4.,  7.,  2.,  0.,  2.,  1.,  4.],
       [ 6.,  3.,  0.,  4.,  2.,  0.,  3.,  7.,  3.,  5.],
       [ 6.,  7.,  5.,  7.,  4.,  3.,  1.,  8.,  5.,  8.],
       [ 3.,  1.,  4.,  0.,  6.,  0.,  3.,  7.,  6.,  1.],
       [ 3.,  3.,  7.,  2.,  8.,  2.,  0.,  5.,  9.,  8.],
       [ 6.,  9.,  1.,  8.,  0.,  0.,  6.,  9.,  4.,  9.],
       [ 9.,  5.,  0.,  2.,  7.,  5.,  1.,  7.,  4.,  2.],
       [ 4.,  7.,  5.,  1.,  3.,  0.,  3.,  0.,  9.,  9.]])

In [256]:
for i in range(10):
    for j in range(10):
        for k in range(10):
            if a[i,j]==0 and i+k < 10 and i-k>=0 and  j+k < 10 and j-k>=0:
                c[i+k,j+k]=0
                c[i-k,j-k]=0
                c[i-k,j+k]=0
                c[i+k,j-k]=0
                           
c

array([[ 0.,  9.,  0.,  5.,  0.,  1.,  2.,  0.,  0.,  3.],
       [ 0.,  0.,  6.,  0.,  0.,  0.,  2.,  0.,  7.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  0.,  2.,  0.,  4.],
       [ 6.,  0.,  0.,  0.,  2.,  0.,  3.,  0.,  3.,  0.],
       [ 6.,  0.,  0.,  0.,  0.,  3.,  0.,  8.,  0.,  8.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  6.,  1.],
       [ 3.,  3.,  0.,  0.,  0.,  0.,  0.,  5.,  0.,  8.],
       [ 6.,  0.,  1.,  0.,  0.,  0.,  6.,  0.,  4.,  9.],
       [ 0.,  5.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  2.],
       [ 4.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  9.,  0.]])

In [257]:
diags = [a[::-1,:].diagonal(i) for i in range(-9,10)]
diags.extend(a.diagonal(i) for i in range(9,-10,-1))
diags


[array([0]),
 array([0, 9]),
 array([0, 4, 1]),
 array([6, 3, 6, 5]),
 array([6, 3, 9, 5, 7]),
 array([3, 7, 0, 4, 4, 1]),
 array([3, 1, 5, 4, 7, 4, 2]),
 array([6, 3, 4, 7, 2, 2, 2, 0]),
 array([9, 9, 7, 0, 4, 0, 0, 3, 7]),
 array([4, 5, 1, 2, 6, 3, 3, 2, 7, 3]),
 array([7, 0, 8, 8, 0, 1, 7, 1, 8]),
 array([5, 2, 0, 2, 3, 8, 3, 4]),
 array([1, 7, 0, 0, 7, 5, 5]),
 array([3, 5, 6, 5, 6, 8]),
 array([0, 1, 9, 9, 1]),
 array([3, 7, 4, 8]),
 array([0, 4, 9]),
 array([9, 2]),
 array([9]),
 array([3]),
 array([7, 8]),
 array([0, 7, 4]),
 array([2, 3, 1, 5]),
 array([1, 2, 2, 3, 8]),
 array([7, 4, 0, 7, 5, 1]),
 array([5, 4, 2, 3, 8, 6, 8]),
 array([1, 5, 7, 0, 1, 7, 9, 9]),
 array([9, 6, 4, 2, 3, 3, 5, 4, 2]),
 array([0, 4, 9, 4, 4, 0, 0, 9, 4, 9]),
 array([0, 3, 0, 7, 6, 2, 6, 7, 9]),
 array([0, 3, 5, 0, 8, 0, 1, 0]),
 array([6, 7, 4, 2, 0, 5, 3]),
 array([6, 1, 7, 8, 7, 0]),
 array([3, 3, 1, 2, 3]),
 array([3, 9, 0, 1]),
 array([6, 5, 5]),
 array([9, 7]),
 array([4])]

In [263]:
diags[3]

array([6, 3, 6, 5])

In [264]:
for x in range(20):
    for y in range(10):
        if diags[x][y]==0:
            diags[x]=0
diags
            

TypeError: 'int' object is not subscriptable

In [237]:
for index, i in enumerate(diags):
    if i==0:
        diags[index]=0
diags

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()