In [10]:
import numpy as np


arr1 = [0]*100
Narr = np.array(arr1).reshape(10,10)
for c in range(3):
    a = np.random.randint(0, 10, 100).reshape(10, 10)
    b = np.copy(a)
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i][j] == 0:
                zeroing(b, i, j)
    Narr += sum([(b == 0)*1])
#print('Primary matrix')
#print(a, end='\n\n\n\n\n')
#print('Modified matrix')
#print(b)
print(Narr)

[[1 0 2 2 2 2 2 0 2 2]
 [1 1 2 3 2 3 1 2 2 3]
 [2 2 2 2 2 2 3 2 3 2]
 [3 2 2 2 0 2 3 3 2 3]
 [2 3 3 1 2 2 3 2 3 1]
 [2 3 3 3 3 3 2 3 2 3]
 [2 0 3 3 3 2 3 0 2 2]
 [0 2 2 3 3 3 1 2 0 3]
 [2 2 3 2 3 3 3 1 2 0]
 [2 3 2 3 0 3 3 2 1 1]]


In [2]:
def zeroing(b, i, j):
    n,m = i,j
    
    while True:
        if n == 0 or m == 0:
            n,m = i,j
            break
        n -= 1
        m -= 1
        b[n][m] = 0
        
    while True:
        if n == 9 or m == 0:
            n,m = i,j
            break
        n += 1
        m -= 1
        b[n][m] = 0
        
    while True:
        if n == 9 or m == 9:
            n,m = i,j
            break
        n += 1
        m += 1
        b[n][m] = 0
        
    while True:
        if n == 0 or m == 9:
            break
        n -= 1
        m += 1
        b[n][m] = 0
        
    return b
    